//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Spans {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Spans() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("msac_tpa_new.Resources.Spans", typeof(Spans).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви впевнені, що хочете видалити?.
        /// </summary>
        public static string AreYouSureToDel {
            get {
                return ResourceManager.GetString("AreYouSureToDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат атестації.
        /// </summary>
        public static string AttestationResult {
            get {
                return ResourceManager.GetString("AttestationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад до списку.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть значення.
        /// </summary>
        public static string ChooseValue {
            get {
                return ResourceManager.GetString("ChooseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата з:.
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата по:.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалено успішно!.
        /// </summary>
        public static string DeletedSuccess {
            get {
                return ResourceManager.GetString("DeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть емейл.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть пароль.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сталася помилка!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий пароль.
        /// </summary>
        public static string NewPassport {
            get {
                return ResourceManager.GetString("NewPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значення не існує в базі!.
        /// </summary>
        public static string NoExists {
            get {
                return ResourceManager.GetString("NoExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл не завантажений.
        /// </summary>
        public static string NoFile {
            get {
                return ResourceManager.GetString("NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибрано не всі параметри!.
        /// </summary>
        public static string NotAllParams {
            get {
                return ResourceManager.GetString("NotAllParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість записів на сторінці.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторіть пароль.
        /// </summary>
        public static string ReenterPassword {
            get {
                return ResourceManager.GetString("ReenterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такий результат уже існує! Повторно не може бути занесений!.
        /// </summary>
        public static string ResultExists {
            get {
                return ResourceManager.GetString("ResultExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спортсмен доданий успішно!.
        /// </summary>
        public static string SportmanAddedSuccess {
            get {
                return ResourceManager.GetString("SportmanAddedSuccess", resourceCulture);
            }
        }
    }
}
