//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Title {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Title() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("msac_tpa_new.Resources.Title", typeof(Title).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновити.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити комісію.
        /// </summary>
        public static string AddComission {
            get {
                return ResourceManager.GetString("AddComission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати користувача.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Міста.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренери.
        /// </summary>
        public static string Coaches {
            get {
                return ResourceManager.GetString("Coaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комісія.
        /// </summary>
        public static string Comission {
            get {
                return ResourceManager.GetString("Comission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комісії.
        /// </summary>
        public static string Comissions {
            get {
                return ResourceManager.GetString("Comissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змагання.
        /// </summary>
        public static string Competitions {
            get {
                return ResourceManager.GetString("Competitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати тренера.
        /// </summary>
        public static string createCoach {
            get {
                return ResourceManager.GetString("createCoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити комісію.
        /// </summary>
        public static string CreateComission {
            get {
                return ResourceManager.GetString("CreateComission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати змагання.
        /// </summary>
        public static string createCompetition {
            get {
                return ResourceManager.GetString("createCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати ФСТ.
        /// </summary>
        public static string createFst {
            get {
                return ResourceManager.GetString("createFst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати спортсмена.
        /// </summary>
        public static string createSportman {
            get {
                return ResourceManager.GetString("createSportman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати команду.
        /// </summary>
        public static string createTeam {
            get {
                return ResourceManager.GetString("createTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалення тренера.
        /// </summary>
        public static string deleteCoach {
            get {
                return ResourceManager.GetString("deleteCoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити комісію.
        /// </summary>
        public static string DeleteComission {
            get {
                return ResourceManager.GetString("DeleteComission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалення змагання.
        /// </summary>
        public static string deleteCompetition {
            get {
                return ResourceManager.GetString("deleteCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалення ФСТ.
        /// </summary>
        public static string deleteFST {
            get {
                return ResourceManager.GetString("deleteFST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалення спортсмена.
        /// </summary>
        public static string deleteSportman {
            get {
                return ResourceManager.GetString("deleteSportman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалення команди.
        /// </summary>
        public static string deleteTeam {
            get {
                return ResourceManager.GetString("deleteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детально.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФСТ.
        /// </summary>
        public static string FST {
            get {
                return ResourceManager.GetString("FST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звіти.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спортсмен.
        /// </summary>
        public static string Sportsman {
            get {
                return ResourceManager.GetString("Sportsman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спортсмени.
        /// </summary>
        public static string Sportsmen {
            get {
                return ResourceManager.GetString("Sportsmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команди.
        /// </summary>
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновити.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновити дані про тренера.
        /// </summary>
        public static string UpdateCoach {
            get {
                return ResourceManager.GetString("UpdateCoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оновити комісію.
        /// </summary>
        public static string UpdateComission {
            get {
                return ResourceManager.GetString("UpdateComission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновити дані про змагання.
        /// </summary>
        public static string UpdateCompetition {
            get {
                return ResourceManager.GetString("UpdateCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновити дані про ФСТ.
        /// </summary>
        public static string UpdateFst {
            get {
                return ResourceManager.GetString("UpdateFst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновити дані про спортсмена.
        /// </summary>
        public static string UpdateSportman {
            get {
                return ResourceManager.GetString("UpdateSportman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновити дані про команду.
        /// </summary>
        public static string UpdateTeam {
            get {
                return ResourceManager.GetString("UpdateTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувачі.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
