// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using msac_tpa.DAL.EF;

namespace msac_tpa_new.Migrations
{
    [DbContext(typeof(SportmenContext))]
    [Migration("20190914211427_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("msac_tpa.DAL.Entities.Attestation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ComissionId");

                    b.Property<string>("DecisionFilePath");

                    b.Property<DateTime>("IssueDate");

                    b.Property<string>("OrderFilePath");

                    b.HasKey("Id");

                    b.HasIndex("ComissionId");

                    b.ToTable("Attestations");
                });

            modelBuilder.Entity("msac_tpa.DAL.Entities.AttestationUserBelt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttestationId");

                    b.Property<int>("BeltId");

                    b.Property<int>("SportManId");

                    b.HasKey("Id");

                    b.HasIndex("AttestationId");

                    b.HasIndex("BeltId");

                    b.HasIndex("SportManId");

                    b.ToTable("AttestationUserBelts");
                });

            modelBuilder.Entity("msac_tpa.DAL.Entities.Belt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Belts");
                });

            modelBuilder.Entity("msac_tpa.DAL.Entities.Comission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("RegionId");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Comissions");
                });

            modelBuilder.Entity("msac_tpa.DAL.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("msac_tpa.DAL.Entities.Sportman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AvatarFilePath");

                    b.Property<DateTime>("BirthDay");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("RegionId");

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("SportMans");
                });

            modelBuilder.Entity("msac_tpa_new.Entities.SportmanComission", b =>
                {
                    b.Property<int>("SportmanId");

                    b.Property<int>("ComissionId");

                    b.Property<int>("Id");

                    b.HasKey("SportmanId", "ComissionId");

                    b.HasIndex("ComissionId");

                    b.ToTable("SportmanComissions");
                });

            modelBuilder.Entity("msac_tpa.DAL.Entities.Attestation", b =>
                {
                    b.HasOne("msac_tpa.DAL.Entities.Comission", "Comission")
                        .WithMany("Attestations")
                        .HasForeignKey("ComissionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("msac_tpa.DAL.Entities.AttestationUserBelt", b =>
                {
                    b.HasOne("msac_tpa.DAL.Entities.Attestation", "Attestation")
                        .WithMany("AttestationUserBelts")
                        .HasForeignKey("AttestationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("msac_tpa.DAL.Entities.Belt", "Belt")
                        .WithMany("AttestationUserBelts")
                        .HasForeignKey("BeltId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("msac_tpa.DAL.Entities.Sportman", "SportMan")
                        .WithMany("AttestationUserBelts")
                        .HasForeignKey("SportManId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("msac_tpa.DAL.Entities.Comission", b =>
                {
                    b.HasOne("msac_tpa.DAL.Entities.Region", "Region")
                        .WithMany("Comissions")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("msac_tpa.DAL.Entities.Sportman", b =>
                {
                    b.HasOne("msac_tpa.DAL.Entities.Region", "Region")
                        .WithMany("Sportmans")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("msac_tpa_new.Entities.SportmanComission", b =>
                {
                    b.HasOne("msac_tpa.DAL.Entities.Comission", "Comission")
                        .WithMany("SportmanComissions")
                        .HasForeignKey("ComissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("msac_tpa.DAL.Entities.Sportman", "Sportman")
                        .WithMany("SportmanComissions")
                        .HasForeignKey("SportmanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
